//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToSamaraApiServer.DeserializeClasses
{
    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class stops
    {

        private stopsStop[] stopField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stop")]
        public stopsStop[] stop
        {
            get
            {
                return this.stopField;
            }
            set
            {
                this.stopField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class stopsStop
    {

        private ushort kS_IDField;

        private string titleField;

        private string adjacentStreetField;

        private string directionField;

        private string titleEnField;

        private string adjacentStreetEnField;

        private string directionEnField;

        private string titleEsField;

        private string adjacentStreetEsField;

        private string directionEsField;

        private object clusterField;

        private string busesMunicipalField;

        private string busesCommercialField;

        private string busesPrigorodField;

        private string busesSeasonField;

        private string busesSpecialField;

        private object busesIntercityField;

        private string tramsField;

        private string trolleybusesField;

        private string metrosField;

        private string electricTrainsField;

        private object riverTransportsField;

        private string infotabloExistsField;

        private decimal latitudeField;

        private decimal longitudeField;

        private string angleField;

        /// <remarks/>
        public ushort KS_ID
        {
            get
            {
                return this.kS_IDField;
            }
            set
            {
                this.kS_IDField = value;
            }
        }

        /// <remarks/>
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string adjacentStreet
        {
            get
            {
                return this.adjacentStreetField;
            }
            set
            {
                this.adjacentStreetField = value;
            }
        }

        /// <remarks/>
        public string direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }

        /// <remarks/>
        public string titleEn
        {
            get
            {
                return this.titleEnField;
            }
            set
            {
                this.titleEnField = value;
            }
        }

        /// <remarks/>
        public string adjacentStreetEn
        {
            get
            {
                return this.adjacentStreetEnField;
            }
            set
            {
                this.adjacentStreetEnField = value;
            }
        }

        /// <remarks/>
        public string directionEn
        {
            get
            {
                return this.directionEnField;
            }
            set
            {
                this.directionEnField = value;
            }
        }

        /// <remarks/>
        public string titleEs
        {
            get
            {
                return this.titleEsField;
            }
            set
            {
                this.titleEsField = value;
            }
        }

        /// <remarks/>
        public string adjacentStreetEs
        {
            get
            {
                return this.adjacentStreetEsField;
            }
            set
            {
                this.adjacentStreetEsField = value;
            }
        }

        /// <remarks/>
        public string directionEs
        {
            get
            {
                return this.directionEsField;
            }
            set
            {
                this.directionEsField = value;
            }
        }

        /// <remarks/>
        public object cluster
        {
            get
            {
                return this.clusterField;
            }
            set
            {
                this.clusterField = value;
            }
        }

        /// <remarks/>
        public string busesMunicipal
        {
            get
            {
                return this.busesMunicipalField;
            }
            set
            {
                this.busesMunicipalField = value;
            }
        }

        /// <remarks/>
        public string busesCommercial
        {
            get
            {
                return this.busesCommercialField;
            }
            set
            {
                this.busesCommercialField = value;
            }
        }

        /// <remarks/>
        public string busesPrigorod
        {
            get
            {
                return this.busesPrigorodField;
            }
            set
            {
                this.busesPrigorodField = value;
            }
        }

        /// <remarks/>
        public string busesSeason
        {
            get
            {
                return this.busesSeasonField;
            }
            set
            {
                this.busesSeasonField = value;
            }
        }

        /// <remarks/>
        public string busesSpecial
        {
            get
            {
                return this.busesSpecialField;
            }
            set
            {
                this.busesSpecialField = value;
            }
        }

        /// <remarks/>
        public object busesIntercity
        {
            get
            {
                return this.busesIntercityField;
            }
            set
            {
                this.busesIntercityField = value;
            }
        }

        /// <remarks/>
        public string trams
        {
            get
            {
                return this.tramsField;
            }
            set
            {
                this.tramsField = value;
            }
        }

        /// <remarks/>
        public string trolleybuses
        {
            get
            {
                return this.trolleybusesField;
            }
            set
            {
                this.trolleybusesField = value;
            }
        }

        /// <remarks/>
        public string metros
        {
            get
            {
                return this.metrosField;
            }
            set
            {
                this.metrosField = value;
            }
        }

        /// <remarks/>
        public string electricTrains
        {
            get
            {
                return this.electricTrainsField;
            }
            set
            {
                this.electricTrainsField = value;
            }
        }

        /// <remarks/>
        public object riverTransports
        {
            get
            {
                return this.riverTransportsField;
            }
            set
            {
                this.riverTransportsField = value;
            }
        }

        /// <remarks/>
        public string infotabloExists
        {
            get
            {
                return this.infotabloExistsField;
            }
            set
            {
                this.infotabloExistsField = value;
            }
        }

        /// <remarks/>
        public decimal latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }

        /// <remarks/>
        public decimal longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }

        /// <remarks/>
        public string angle
        {
            get
            {
                return this.angleField;
            }
            set
            {
                this.angleField = value;
            }
        }
    }
}
