//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace ToSamaraApiServer.DeserializeClasses
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class routes
    {

        private routesRoute[] routeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("route")]
        public routesRoute[] route
        {
            get
            {
                return this.routeField;
            }
            set
            {
                this.routeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class routesRoute
    {

        private ushort kR_IDField;

        private string numberField;

        private string directionField;

        private string directionEnField;

        private string directionEsField;

        private byte transportTypeIDField;

        private string transportTypeField;

        private byte affiliationIDField;

        private string affiliationField;

        private byte realtimeForecastField;

        /// <remarks/>
        public ushort KR_ID
        {
            get
            {
                return this.kR_IDField;
            }
            set
            {
                this.kR_IDField = value;
            }
        }

        /// <remarks/>
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        public string direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }

        /// <remarks/>
        public string directionEn
        {
            get
            {
                return this.directionEnField;
            }
            set
            {
                this.directionEnField = value;
            }
        }

        /// <remarks/>
        public string directionEs
        {
            get
            {
                return this.directionEsField;
            }
            set
            {
                this.directionEsField = value;
            }
        }

        /// <remarks/>
        public byte transportTypeID
        {
            get
            {
                return this.transportTypeIDField;
            }
            set
            {
                this.transportTypeIDField = value;
            }
        }

        /// <remarks/>
        public string transportType
        {
            get
            {
                return this.transportTypeField;
            }
            set
            {
                this.transportTypeField = value;
            }
        }

        /// <remarks/>
        public byte affiliationID
        {
            get
            {
                return this.affiliationIDField;
            }
            set
            {
                this.affiliationIDField = value;
            }
        }

        /// <remarks/>
        public string affiliation
        {
            get
            {
                return this.affiliationField;
            }
            set
            {
                this.affiliationField = value;
            }
        }

        /// <remarks/>
        public byte realtimeForecast
        {
            get
            {
                return this.realtimeForecastField;
            }
            set
            {
                this.realtimeForecastField = value;
            }
        }
    }
}